# export destination directory for reformatted immunoscore results
export_dir: "./definiens_results_export"

# source immunoscore directory
base_dir: "/Volumes/I$/Christopher Paustian/Colon Immunoscore  4-21-2014/CRC 61-65"
# data base name
database_name: "immunoscore_results_aggregator"


