# destination for reformatted immunoscore results
export_dir: "./definiens_results_export"
# source immunoscore directory
base_dir: "/Volumes/cbb_transfer"
# data base name
database_name: "immunoscore_results"


